services:
  metransfer:
    image: andrepadua/metransfer:latest
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      - INSTALL_DIR=/data # Needed for Container deployment. Do not change this value.
    volumes:
      - ${GALLERY_DIR:-./data}:/data # Change this to your desired directory for storing the gallery data. Do not change the left side of the mapping.
